name: 'Update File Content'
description: 'Update a file in the repository with new content'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  file-path:
    description: 'Path to the file to update'
    required: true
  file-content:
    description: 'New content for the file'
    required: true
  commit-message:
    description: 'Commit message for the update'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'