name: 'Assistant File Update'
description: 'Update a file in the repository with content processed by an AI assistant'
inputs:
  github-token:
    description: 'GitHub token for repository access'
    required: true
  file-path:
    description: 'Path to the file to update'
    required: true
  commit-message:
    description: 'Commit message for the update'
    required: true
runs:
  using: 'node16'
  main: 'dist/actions.js'
