const core = require("@actions/core");
const github = require("@actions/github");
const { fullAssistantProcessor } = require("./utils/fullAssistantProcessor");
const { config } = require("./utils/config");

async function run() {
    try {
        const token = core.getInput("github-token", { required: true });
        const commitMessage = core.getInput("commit-message", {
            required: true,
        });

        if (!config.implementationFile) {
            throw new Error("No failed test implementation file found to update");
        }

        // Process with the assistant
        const newData = await fullAssistantProcessor();

        if (!newData) {
            throw new Error(
                "No new data was returned from the assistant processor"
            );
        }

        const octokit = github.getOctokit(token);
        const { owner, repo } = github.context.repo;
        
        // Explicitly get the default branch
        const { data: repoData } = await octokit.rest.repos.get({
            owner,
            repo
        });
        const baseBranch = repoData.default_branch;
        const newBranchName = `ai-fix-${Date.now()}`;

        // Create a new branch
        const { data: baseRef } = await octokit.rest.git.getRef({
            owner,
            repo,
            ref: `heads/${baseBranch}`
        });

        await octokit.rest.git.createRef({
            owner,
            repo,
            ref: `refs/heads/${newBranchName}`,
            sha: baseRef.sha
        });

        const filePath = config.implementationFile;

        // Create or update file in the new branch
        await octokit.rest.repos.createOrUpdateFileContents({
            owner,
            repo,
            path: filePath,
            message: commitMessage,
            content: Buffer.from(newData).toString("base64"),
            branch: newBranchName
        });

        // Create a pull request
        await octokit.rest.pulls.create({
            owner,
            repo,
            title: commitMessage,
            head: newBranchName,
            base: baseBranch,
            body: "Automated fix generated by AI assistant based on test failures"
        });

        console.log(
            `File ${filePath} updated in new branch ${newBranchName}. Pull request created.`
        );

    } catch (error) {
        core.setFailed(error.message);
    }
}

run();