name: Process Feedback

on:
    issue_comment:
        types: [created]

permissions:
    contents: write
    actions: write
    pull-requests: write

jobs:
    process-feedback:
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '[FEEDBACK]') }}
        runs-on: ubuntu-latest
        steps:
            - name: React to comment
              uses: peter-evans/create-or-update-comment@v2
              with:
                comment-id: ${{ github.event.comment.id }}
                reactions: '+1'

            - name: Notify processing started
              uses: peter-evans/create-or-update-comment@v2
              with:
                issue-number: ${{ github.event.issue.number }}
                body: "📝 Received feedback! Processing code changes..."
            
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Get PR details and workflow run
              id: pr_details
              run: |
                gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
                
                # Get PR branch and other details
                pr_data=$(gh pr view ${{ github.event.issue.number }} --json headRefName,headRepository,headRefOid)
                branch_name=$(echo "$pr_data" | jq -r .headRefName)
                
                # Find the most recent successful run of the Update Failed Implementation workflow
                workflow_runs=$(gh run list --workflow "Update Failed Implementation" --branch "$branch_name" --json conclusion,databaseId,status --jq '[.[] | select(.status=="completed")]')
                run_id=$(echo "$workflow_runs" | jq -r '.[0].databaseId')
                
                echo "run_id=$run_id" >> $GITHUB_OUTPUT
                echo "Found workflow run ID: $run_id"

            - name: Download pytest report
              uses: actions/download-artifact@v4
              with:
                name: pytest-report
                path: pytest_report
                github-token: ${{ secrets.GITHUB_TOKEN }}
                run-id: ${{ steps.pr_details.outputs.run_id }}

            - name: Get PR branch and create new branch
              id: get_pr_branch
              run: |
                # Get PR branch name
                gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
                pr_data=$(gh pr view ${{ github.event.issue.number }} --json headRefName,title)
                current_branch=$(echo $pr_data | jq -r .headRefName)
                
                # Verify this is an AIFIX branch
                if [[ "$current_branch" != *"-AIFIX-"* ]]; then
                  echo "Error: Feedback only works on AIFIX branches"
                  exit 1
                fi
                
                # Create new branch with feedback suffix
                new_branch="${current_branch}-feedback"
                
                # Checkout and create the new branch
                git fetch origin $current_branch
                git checkout $current_branch
                git checkout -b $new_branch
                git push -u origin $new_branch
                
                echo "current_branch=$current_branch" >> $GITHUB_OUTPUT
                echo "new_branch=$new_branch" >> $GITHUB_OUTPUT

            - name: Run update implementation
              uses: ./ # Uses the action in the root directory
              env:
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
              with:
                target-branch: ${{ steps.get_pr_branch.outputs.new_branch }}
                github-token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: "[AIFIX] Applying feedback from comment"
                feedback: ${{ github.event.comment.body }}
            
            - name: Create New Pull Request
              run: |
                gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"
                gh pr create \
                  --base main \
                  --head ${{ steps.get_pr_branch.outputs.new_branch }} \
                  --title "[AIFIX] Updated fix with feedback for PR #${{ github.event.issue.number }}" \
                  --body "This is an updated AI-generated fix incorporating feedback from PR #${{ github.event.issue.number }}."

            - name: Close Original Pull Request
              run: |
                gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
                gh pr close ${{ github.event.issue.number }} --comment "Closing this PR as a new AI-assisted fix with feedback has been created in branch ${{ steps.get_pr_branch.outputs.new_branch }}. Please review the new changes there."

