name: Update Failed Implementation

on:
    workflow_dispatch:
        inputs:
            commit-message:
                description: "Commit message for the update"
                required: true
                default: "fix: Update implementation file with AI-assisted fix"

permissions:
    contents: write

jobs:

    run-tests:
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        outputs:
            pytest_failed: ${{ steps.pytest_status.outputs.pytest_failed }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.10.4

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run pytest
              run: |
                pytest
              continue-on-error: true
              id: pytest_result

            - name: Check pytest status
              id: pytest_status
              run: |
                if [[ "${{ steps.pytest_result.outcome }}" == "failure" ]]; then
                  echo "pytest_failed=true" >> $GITHUB_OUTPUT
                else
                  echo "pytest_failed=false" >> $GITHUB_OUTPUT
                fi

    update-implementation:
        needs: run-tests
        if: ${{ needs.run-tests.outputs.pytest_failed == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update implementation file
              uses: ./ # Uses the action in the root directory
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: ${{ github.event.inputs.commit-message }}