name: Update Failed Implementation

on:
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    run-tests:
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        outputs:
            pytest_failed: ${{ steps.pytest_status.outputs.pytest_failed }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.10.4

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Ensure pytest_report directory exists
              run: mkdir -p pytest_report

            - name: Run pytest
              run: |
                pytest
              continue-on-error: true
              id: pytest_result

            - name: Check pytest status
              id: pytest_status
              run: |
                if [[ "${{ steps.pytest_result.outcome }}" == "failure" ]]; then
                  echo "pytest_failed=true" >> $GITHUB_OUTPUT
                else
                  echo "pytest_failed=false" >> $GITHUB_OUTPUT
                fi

            - name: Upload pytest report artifact
              uses: actions/upload-artifact@v4
              with:
                name: pytest-report
                path: src/pytest_report/report.json

    update-implementation:
        needs: run-tests
        if: ${{ needs.run-tests.outputs.pytest_failed == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download pytest report artifact
              uses: actions/download-artifact@v4
              with:
                name: pytest-report
                path: pytest_report

            - name: Create AI Fix Branch
              id: create-branch
              run: |
                BRANCH_NAME="${{ github.head_ref || github.ref_name }}-AIFix-$(date +%Y-%m-%d)"
                git checkout -b $BRANCH_NAME
                echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

            - name: Prepare AI-Assisted Fix
              uses: ./ 
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "fix: Prepare AI-assisted implementation update"
                  base-branch: ${{ steps.create-branch.outputs.branch_name }}

            - name: Push New Branch
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git push -f origin ${{ steps.create-branch.outputs.branch_name }}

            # - name: Create Pull Request
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   run: |
            #     gh pr create \
            #       --base ${{ github.event.pull_request.base.ref }} \
            #       --head ${{ steps.create-branch.outputs.branch_name }} \
            #       --title "AI-Assisted Fix for Failed Tests" \
            #       --body "Automated AI-generated fix based on test failures"