name: Update Failed Implementation

on:
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    run-tests:
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        outputs:
            pytest_failed: ${{ steps.pytest_status.outputs.pytest_failed }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.10.4

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Ensure pytest_report directory exists
              run: mkdir -p pytest_report

            - name: Run pytest
              run: |
                pytest
              continue-on-error: true
              id: pytest_result

            - name: Check pytest status
              id: pytest_status
              run: |
                if [[ "${{ steps.pytest_result.outcome }}" == "failure" ]]; then
                  echo "pytest_failed=true" >> $GITHUB_OUTPUT
                else
                  echo "pytest_failed=false" >> $GITHUB_OUTPUT
                fi

            - name: Upload pytest report artifact
              uses: actions/upload-artifact@v4
              with:
                name: pytest-report
                path: src/pytest_report/report.json

    update-implementation:
        needs: run-tests
        if: ${{ needs.run-tests.outputs.pytest_failed == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Create new branch
              run: |
                git checkout -b ai-fix-${{ github.event.pull_request.number }}

            - name: Download pytest report artifact
              uses: actions/download-artifact@v4
              with:
                name: pytest-report
                path: pytest_report

            - name: Update implementation file
              uses: ./ # Uses the action in the root directory
              env:
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: "AI-assisted fix for failed tests"
                target-branch: ai-fix-${{ github.event.pull_request.number }}
      
            - name: Push new branch
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git push -u origin ai-fix-${{ github.event.pull_request.number }}