name: Update Failed Implementation

on:
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    run-tests:
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        outputs:
            pytest_failed: ${{ steps.pytest_status.outputs.pytest_failed }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.10.4

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Ensure pytest_report directory exists
              run: mkdir -p pytest_report

            - name: Run pytest
              run: |
                pytest
              continue-on-error: true
              id: pytest_result

            - name: Check pytest status
              id: pytest_status
              run: |
                if [[ "${{ steps.pytest_result.outcome }}" == "failure" ]]; then
                  echo "pytest_failed=true" >> $GITHUB_OUTPUT
                else
                  echo "pytest_failed=false" >> $GITHUB_OUTPUT
                fi

            - name: Create AI Fix Branch
              id: create_branch
              if: ${{ steps.pytest_status.outputs.pytest_failed == 'true' }}
              run: |
                original_branch="${{ github.head_ref }}"
                branch_name="${original_branch}-AIFIX-${{ github.event.pull_request.number }}"
                git checkout -b $branch_name
                git push -u origin $branch_name
                echo "$branch_name" > ai_fix_branch.txt
                echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
                cat $GITHUB_OUTPUT

            - name : Upload branch name artifact
              uses: actions/upload-artifact@v4
              with:
                name: ai-fix-branch
                path: ai_fix_branch.txt

            - name: Debug Outputs
              run: |
                  echo "pytest_failed: ${{ steps.pytest_status.outputs.pytest_failed }}"

            - name: Upload pytest report artifact
              uses: actions/upload-artifact@v4
              with:
                name: pytest-report
                path: src/pytest_report/report.json

    update-implementation:
        needs: run-tests
        if: ${{ needs.run-tests.outputs.pytest_failed == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Download ai-fix-branch artifact
              uses: actions/download-artifact@v4
              with:
                name: ai-fix-branch

            - name: Download pytest report artifact
              uses: actions/download-artifact@v4
              with:
                name: pytest-report
                path: pytest_report

            - name: Read AI Fix Branch Name
              id: read_branch
              run: |
                branch_name=$(cat ai_fix_branch.txt)
                echo "target_branch=$branch_name" >> $GITHUB_OUTPUT
                echo "Branch name from file: $branch_name"

            - name: Update implementation file
              uses: ./ # Uses the action in the root directory
              env:
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
              with:
                target-branch: ${{ steps.read_branch.outputs.target_branch }}
                github-token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: "AI-assisted fix for failed tests"
