name: Update Failed Implementation

on:
    workflow_dispatch:
        inputs:
            commit-message:
                description: "Commit message for the update"
                required: true
                default: "fix: Update implementation file with AI-assisted fix"

permissions:
    contents: write

jobs:
    update-implementation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Update implementation file
              uses: ./ # Uses the action in the root directory
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: ${{ github.event.inputs.commit-message }}